### PR TITLE
Fix runtimmecompil

### PR DESCRIPTION
**Pull request by pthom**
Hello Sam,

Thanks for putting the video in the readme. I did an improved version.

I also fixed an issue with the sandbox (that I renamed to "playground", in order to have the same name as in Babylon.js) : it was not working in release build.

Cheers

### CODE REVIEW

**Comment by samdauwe** [comment]
Hello Pascal,

thanks for the fixes and your efforts for creating such a nice demo video! The video nicely shows what is currently possible with BabylonCpp.

cheers,
Sam

**Comment by pthom** [comment]
Hello Sam,

I was thinking it might be interesting to post an info about BabylonCpp in the [Dear ImGui Gallery](https://github.com/ocornut/imgui/issues/2847). 

I had prepared a message for this gallery, but I did not post it there, since I thought this should be your decision. Anyhow, here is what I had prepared.  Feel free to do whatever you want with it, and to post it or not :-)

Regards,

--- 
[BabylonCpp](https://github.com/samdauwe/BabylonCpp) - a C++ port of [Babylon.js](https://www.babylonjs.com/) - is a 3D game engine, still in under heavy development, whose GUI is based on Dear ImGui.

It includes a graphical inspector for all 3D objects:

image

An interactive playground for live coding and experiments

image

and more than 200 examples

image



Demo video:

[image
 ](https://www.youtube.com/watch?v=McU8_vIEJfQ&feature=youtu.be)

**Comment by samdauwe** [comment]
Hello Pascal,

Yeah, that is a really good idea! Thank you very much for preparing the description and screenshots.

I created the post with info about BabylonCpp in the [Dear ImGui Gallery](https://github.com/ocornut/imgui/issues/2847).

Hopefully there is a lot of positive feedback on all our work we did :)

Cheers and have nice day,
Sam

**Comment by pthom** [comment]
I took the liberty to post about this in the RuntimeCompiledCPlusPlus repo, [here](https://github.com/RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus/issues/103)

**Comment by samdauwe** [comment]
Nice! It will be added to the RuntimeCompiledCPlusPlus gallery soon :)

**Pull request merged**
