### PR TITLE
Sshot linux: status & screenshots under linux

### PR DESCRIPTION
**Pull request by pthom**
Hello Sam,

This is a PR where I try to have a more clear view about the current status.
It is now possible to take screenshots of all the examples under linux.

How to use it:
* launch `BabylonStudio -a`, and it will create a `Screenshots/` folder with all the screenshots
* For each example, you will get either:
  * a screenshot 
  * a ".Fail.txt" file with the stack trace after failure if the example fails
  * a "TooSlow.txt" file when the rendering did take more than 5 seconds for the first 20 frames

image
 
You can download a zip with the current status here: 
[ScreenShots.zip](https://github.com/samdauwe/BabylonCpp/files/4088155/ScreenShots.zip)

----
Notable modifications in this PR

For this I added two new header only third parties:

- [backward-cpp](https://github.com/bombela/backward-cpp) which gives a nice stack trace. 
You do need to install binutils-dev (`sudo apt-get install binutils-dev`) in order to get the complete output
- [subprocess.h](https://github.com/sheredom/subprocess.h) which gives a way to finely launch processes and check for their output/success/ etc

-----

Status as of now: 149 successes (but with 28 empty renderings) , 121 failures (not only in the loaders actually), 9 too slow

````bash

> cd ScreenShots

> # List sucesses
> ls -1 *.jpg|wc -l
149

> # Find screenshots of less than 1.5Ko (3D rendering is probably empty)
> find . -name "*.jpg" -size -1500c |wc -l
28

> # List hard failures
> ls -1 *.Fail.txt|wc -l
121

> # List timeout (i.e example that render too slow)
> ls -1 *.TooSlow.txt|wc -l
9
````

I hope this is not to disappointing, but I wanted us to have a clear view of the current status.

----

Remark:

We should provide a stable branch for users. The [stable](https://github.com/pthom/BabylonCpp/commits/stable) branch on my fork is a checkout of a commit from Nov 22nd when most of the examples were working. 
May be it would be a good idea to point users to this branch, so that they have a better experience with the library.

Cheers,

Pascal

### CODE REVIEW

**Comment by pthom** [comment]
Note: the success rate seems to be reproducible accross all linux/windows/osx

**Comment by pthom** [comment]
I added a new feature which is that `BabylonStudio -a` will populate the `Screenshots`and add a file `Screenshots/_stats.txt` with the following kind of content:

````json
{
    "nbEmptyRendering": 23,
    "nbProcessFailures": 127,
    "nbProcessHung": 8,
    "nbSuccess": 120
}
````

EmptyRendering is tested automatically: if a screenshot consists of only one homogeneous color, then the 3D rendering is considered empty.

This opens a possibility to make rendering unit tests after CI builds. 

For example we could test that nbSuccess does not decrease, although is a tough choice.

**Comment by samdauwe** [comment]
Hello Pascal,

Thanks for the pull request, those are really useful changes!

I agree, end of November we had a much more stable version. Having the option to create the screenshots will help keeping the master branch stable.

I will update the main page with the link to the stable version so we can focus on getting those examples issues fixed. Once fixed we can move to a 'dev' branch.

Cheers,
Sam

**Comment by pthom** [comment]
I'm still working on this branch, in order to fix the CI.

**Comment by samdauwe** [comment]
I fixed an issue related to creating VertexData from map data with [this commit](https://github.com/samdauwe/BabylonCpp/commit/a345ded74e812bbf56d67b28779efd1fbd454558). That should fix 3 examples: HeightMapScene, LightProjectedTextureScene and RaycastOnHeightMapScene.

When debugging I notice that a lot of issues are related to loading files, like callbacks that use properties that are not valid anymore (although capturing is by value instead of reference).

I can try to fix those asset loading issues or do you think it is better to 'redesign' the asset loading so we need less callbacks that can cause issues?

ps: I updated the readme to point to your stable branch.

Cheers,
Sam

**Comment by pthom** [comment]
> I fixed an issue related to creating VertexData from map data with this commit. That should fix 3 examples: HeightMapScene, LightProjectedTextureScene and RaycastOnHeightMapScene.

Good! Could we try to run `BabylonStudio -a` periodically, and to note its stats output in the comments, so that we can keep track of the stats? It is not 100% accurate, but it might help anyhow.

> When debugging I notice that a lot of issues are related to loading files, like callbacks that use properties that are not valid anymore (although capturing is by value instead of reference).

As you can see in [this PR](https://github.com/samdauwe/BabylonCpp/pull/75), there are still some [capture](https://github.com/samdauwe/BabylonCpp/pull/75/commits/a60a911a24279a779eeda6ea8d2223d2ef5bfc95) and [iterator](https://github.com/samdauwe/BabylonCpp/pull/75/commits/b08b742c18714d98ce1cbb2d62af614dfcadd749) issues. We'd better get rid of those first by concentrating first on the samples that do not require loading assets.

 > I can try to fix those asset loading issues or do you think it is better to 'redesign' the asset loading so we need less callbacks that can cause issues?

I do not know yet...

May be one of my commits could lead to a possible more thorough understanding.

When fixing `morph_mesh_scene.cpp` (see https://github.com/samdauwe/BabylonCpp/pull/75/commits/508c44d5bc40b994c71295749693deaf86be2a77?file-filters%5B%5D=#diff-36d953b10e691c80f56bb6a7db80e670) I saw 2 lambdas:

````cpp
    SceneLoader::ImportMesh(
      {"Sphere Default", "Sphere Morph"}, "scenes/", "morph.babylon", scene,
      [this, scene](const std::vector<AbstractMeshPtr>& /*meshes*/,
                    const std::vector<IParticleSystemPtr>& /*particleSystems*/,
                    const std::vector<SkeletonPtr>& /*skeletons*/,
                    const std::vector<AnimationGroupPtr>& /*animationGroups*/) {
        auto test = std::static_pointer_cast<Mesh>(scene->getMeshByName("Sphere Default"));
       // etc.
````

and 

````cpp
    scene->registerBeforeRender([this](Scene* /*scene*/, EventState& /*es*/) {
      auto currentTimestamp = Time::highresTimepointNow();
      auto diffMillis = Time::fpTimeDiff<size_t, std::milli>(_previousTimestamp, currentTimestamp);
     // etc.
````

I suppose that the lambda created for `scene->registerBeforeRender` was supposed to be called only after the lambda created for `SceneLoader::ImportMesh`, but it is not the case (thus the awkard null test). 
If my analysis is right, then, yes, there is an issue in the callbacks order that might need more thinking.

**Comment by samdauwe** [comment]
> > I fixed an issue related to creating VertexData from map data with this commit. That should fix 3 examples: HeightMapScene, LightProjectedTextureScene and RaycastOnHeightMapScene.
> 
> Good! Could we try to run `BabylonStudio -a` periodically, and to note its stats output in the comments, so that we can keep track of the stats? It is not 100% accurate, but it might help anyhow.

Great idea!

I fixed the following 3 examples today:
- RealtimeReflectionScene with [this commit](https://github.com/samdauwe/BabylonCpp/commit/f06b312605ac2a178c69bf6fa43f23928664d407)
- RealtimeRefractionScene with [this commit](https://github.com/samdauwe/BabylonCpp/commit/f06b312605ac2a178c69bf6fa43f23928664d407)
- SimpleCarFollowingPathScene with [this commit](https://github.com/samdauwe/BabylonCpp/commit/d83200bd46f6bb000243e9bea35493b64ebe0df5)

Then I looked into the file loading issues but I did not come to a solution yet...

> > When debugging I notice that a lot of issues are related to loading files, like callbacks that use properties that are not valid anymore (although capturing is by value instead of reference).
> 
> As you can see in [this PR](https://github.com/samdauwe/BabylonCpp/pull/75), there are still some [capture](https://github.com/samdauwe/BabylonCpp/pull/75/commits/a60a911a24279a779eeda6ea8d2223d2ef5bfc95) and [iterator](https://github.com/samdauwe/BabylonCpp/pull/75/commits/b08b742c18714d98ce1cbb2d62af614dfcadd749) issues. We'd better get rid of those first by concentrating first on the samples that do not require loading assets.

Ok, good plan, I will focus on those errors for now.

> > I can try to fix those asset loading issues or do you think it is better to 'redesign' the asset loading so we need less callbacks that can cause issues?
> 
> I do not know yet...
> 
> May be one of my commits could lead to a possible more thorough understanding.
> 
> When fixing `morph_mesh_scene.cpp` (see [508c44d?file-filters%5B%5D=#diff-36d953b10e691c80f56bb6a7db80e670](https://github.com/samdauwe/BabylonCpp/commit/508c44d5bc40b994c71295749693deaf86be2a77?file-filters%5B%5D=#diff-36d953b10e691c80f56bb6a7db80e670)) I saw 2 lambdas:
> 
> ```c++
>     SceneLoader::ImportMesh(
>       {"Sphere Default", "Sphere Morph"}, "scenes/", "morph.babylon", scene,
>       [this, scene](const std::vector<AbstractMeshPtr>& /*meshes*/,
>                     const std::vector<IParticleSystemPtr>& /*particleSystems*/,
>                     const std::vector<SkeletonPtr>& /*skeletons*/,
>                     const std::vector<AnimationGroupPtr>& /*animationGroups*/) {
>         auto test = std::static_pointer_cast<Mesh>(scene->getMeshByName("Sphere Default"));
>        // etc.
> ```
> 
> and
> 
> ```c++
>     scene->registerBeforeRender([this](Scene* /*scene*/, EventState& /*es*/) {
>       auto currentTimestamp = Time::highresTimepointNow();
>       auto diffMillis = Time::fpTimeDiff<size_t, std::milli>(_previousTimestamp, currentTimestamp);
>      // etc.
> ```
> 
> I suppose that the lambda created for `scene->registerBeforeRender` was supposed to be called only after the lambda created for `SceneLoader::ImportMesh`, but it is not the case (thus the awkard null test).
> If my analysis is right, then, yes, there is an issue in the callbacks order that might need more thinking.

Yes, you are right! In the scene class there is the variabele '_pendingData'. When a texture is loaded then it is put in the _pendingData list and it is removed when fully loaded. Only when the _pendingData list is empty the renderloop runs and the 'registerBeforeRender' function is called.

Debugging the file loading with all the callbacks and the asynchronous execution of code is not that easy. I will have to think more how to make it easier.

Cheers,
Sam

**Pull request merged**
