### PR TITLE
Sample enabled

### PR DESCRIPTION
**Pull request by pthom**
Hello again,

Here is another PR where I disabled the old "isEnabled" flag on the samples, because theses examples were never showing in the samples browser. The are now classified as passing or failing as the others.

This adds :
- 12 new passing examples 👍 
- 11 new failing example 👎

### CODE REVIEW

**Comment by pthom** [comment]
This PR still needs some work. I'm on it.

**Comment by pthom** [comment]
On a different subject, I would advise to change the screenshot in the Readme for a more interactive version, such as https://www.youtube.com/watch?v=HwvctC80qho&feature=youtu.be
What do you think?

**Comment by pthom** [comment]
I also added the gltf loader examples under windows. For the moment, the rendering is empty under MSVC (it works under osx). 
Do you have an idea about the reason why it fails?

**Comment by samdauwe** [comment]
> On a different subject, I would advise to change the screenshot in the Readme for a more interactive version, such as https://www.youtube.com/watch?v=HwvctC80qho&feature=youtu.be
> What do you think?

Wow, that is a nice video you made!

I updated the Readme file to link to the video. What do you think?

**Comment by samdauwe** [comment]
> I also added the gltf loader examples under windows. For the moment, the rendering is empty under MSVC (it works under osx).
> Do you have an idea about the reason why it fails?

I will further investigate on my side and will let you know when the issue is resolved in the next couple of days.

**Pull request merged**
