### PR TITLE
Imgui engine

### PR DESCRIPTION
**Pull request by pthom**
Hi,

As I told you, I was working on integrating the inspector into a full imgui app. I have a working branch, and I am quite pleased with the result. 

I hope you will like it!

image

# Video demonstration and lots of details

This required quite a lot of work, and I had to reorganize some libraries. It would be too long to describe the new features and the code modificaitons inside this message; so I did some videos in order to demonstrate them to you. I hope you will find this effective.

* First video : demonstration of the new feature, and demonstration of the code modifications

[image](https://traineq.org/BabCpp_engine_vid1.mp4)

(12 minutes)

* Second video : some remarks

[image](https://traineq.org/BabCpp_engine_vid2.mp4)

(6 minutes)

# Notes

* `BabylonImGuiList/CMakeLists.txt`need to be corrected : I disabled the install part, because of a bug I could not solve. Could you have a look at it?
* May be `src/SampleLauncher/include/babylon/impl/gl_rendering_context.h` should be removed, since `src/BabylonImGui/include/babylon/GL/gl_rendering_context.h`is a copy of it that is included inside a library

* One of your latest commits ( [Updating Scene class to v4.0.0](https://github.com/samdauwe/BabylonCpp/commit/c873d5e87fcf13625b77b93a8d516204499f47ac) ) broke the rendering on my side (the 3d scene is shown as empty) . This merge request is thus voluntarily based on a older commit of the master branch.

### CODE REVIEW

**Comment by pthom** [comment]
Please do look at the videos, they do give a lot of details and explanations.

As a reminder, I include below a summary of the modified source code sections

### top level view




I added a new submodule (https://github.com/BalazsJako/ImGuiColorTextEdit.git , a code editor)

### screenshots


I added some new screenshots, taken from the cpp application under windows. They show the current status of the samples that run or fail.

### src


* `BabylonCpp/` and `SampleLauncher` were almost not modified.
* `imgui_utils`,  `BabylonImGui` (old `inspector`library) and `SamplesRunner` were heavily modified

### BabylonCpp


`BabylonCpp/` was almost not modified. I added some utilities (CL11.h, system.h, init_console_logger)

### imgui_utils


ìmgui_utils` is a set of utilities for ImGui, which are totaly independent from BabylonCpp.

* `imgui_runner` : run an ImGui application with 5 lines of code
* `code_editor` : multi-file wrapper around  ImGuiColorTextEdit

### BabylonImGui


`BabylonImGui` (which includes the old `inspector` library) provides:

* the inspector tabs
* the main GUI (see `src/BabylonImGui/src/babylon_imgui/run_scene_with_inspector.cpp`)
* an ImGui widget that is able to display a 3D scene (`imgui_scene_widget`)
* `FramebufferCanvas` : a derivate of `ICanvas` that uses an OpenGL FrameBuffer
* `gl_rendering_context.h`: the OpenGl backend

Note: may be FramebufferCanvas and gl_rendering_context could be extracted to a separate library dedicated to the OpenGL backend.

### SampleLauncher


I did not modify this project. It still includes a _duplicate_ version of `gl_rendering_context`.

### Samples


Minor adaptations (unique_ptr => shared_ptr)

### SamplesRunner


`SamplesRunner` is meant to replace `SampleLauncher`.

I tried to make these files as simple and didactic as possible, so that new users can understand the library and try new things easily. It includes an "HelloScene" as a starting point (so that users can play with it).

**Comment by pthom** [comment]
Oups, I just stumbled upon your message in my last PR. It seems I worked on exactly the same subject as you. I hope there will not be too many conflicts.
Sorry for the trouble, I did not receive any notification about your message (I guess this is because the PR was closed)

**Comment by samdauwe** [comment]
Hi Pascal,

Wow, this is amazing work!!! I really like the improvements that you made. Thanks for all the time you put into theses changes and for making the very informative videos! The videos make it much easier to understand all your changes compared to reading a wall of text.

I like the index you added, this should save a lot of typing, also the code editor is very usefull as the links to the online sources!

I agree with you, after seeing your ImGui engine we can deprecate the old Sampleslauncher :)

Good to know you came to the same conclusion as me to use OpenGL framebuffers to render the scene to a texture, so it can be shown in ImGui. I noticed that you were working on something similar as me in your code so I did not continue with further integration.

Regarding the remarks:
- Indeed, the cmake script could be simplified. Something to think about for the future.
- On Windows there are more samples failing compared to Linux. Thanks for making the list and the comparison screenshots. This should get me started for a round of sample debugging.
- Code quality could be improved (i.e. usage of correct smart pointers). I will certainly take the advice about multiline strings and sample headers into account. The diagrams also seem useful, they probably can be generated through automatic scripting as part of the build.

About more visibility of the BabylonCpp project. I totally agree with you on that. The creators of the BabylonJS project already know a long time about the existence of this port. I also [communicated](http://www.html5gamedevs.com/topic/40178-babyloncpp-a-port-of-babylonjs-to-c/) it to the community almost a year ago. The reactions were positive but there were not much volunteers to actually try BabylonCpp or contribute.

As I see it now, BabylonJS is moving too fast for me. And more core developers are joining the team . Porting the code to a new version takes me normally 3-4 months in my free time, then it takes some weeks to fix samples that are broken. So not much time is left for making nice demos before the next release. With Babylon native I could make extensions using a native language without having to port the core library. I have not decided yet how to proceed with this.

About the port to BabylonJS v4.0.0 I am finishing the Scene class port and then I am finished with the update to v4.0.0. By accident I did a commit in the master branch instead of the '4.0.0/rendering_issues' branch, so like you already mentioned that commit ( Updating Scene class to v4.0.0 ) should be undone. This is something for this weekend, I will also merge your pull request this weekend.

Many thanks for all your hard work and have a nice weekend,
Sam

**Comment by pthom** [comment]
I just added a new branch [imgui_engine_merge](https://github.com/pthom/BabylonCpp/tree/imgui_engine_merge) where I made the necessary adaptation to merge my branch to master. However, the rendering is still broken.

**Comment by samdauwe** [comment]
I finished the port tot v4.0.0 in master. On Linux the very basic examples render. Going to focus on Windows so I can merge all your pull requests. I will get back to you tomorrow when I have more time.

thanks,
Sam

**Comment by samdauwe** [comment]
Hi again,

Some updates from my side.

I merged [Imgui engine](https://github.com/samdauwe/BabylonCpp/pull/31) and [Fix split](https://github.com/samdauwe/BabylonCpp/pull/35) pull requests into the master branch.

I did some testing but found many issues:
- The old SampleLauncher is able to render the BasicScene on both Windows and Linux. However, the mouse input is broken, maybe an issue with the sensitivity of the mouse.
- The new SampleRunner only renders the scene properly the first iteration of the render loop. From the second iteration you only get the clear color. This can be observed by opening for instance the sample 'AnimatedMorphTargetScene', you will see the sphere and then it disappears. As it was working before I have to do some testing what changes in the Engine class is causing this issue.
- Many samples are broken.

I am going to continue trying to resolve those issues.

Best regards,
Sam

**Comment by pthom** [comment]
Hello,

On my side, the rendering is broken on windows even for the basic scene. It does work on linux and osx for the basic scene however.

One advice that could help: ask `glad` to track all the OpenGl errors and stop whenever one is encountered.

Steps for this:

* rename external/glad/ to external/glad.release/
* rename external/glad.debug to external/glad/
* add a breakpoint in `glad_post_call_callback` (src/BabylonImGui/src/GL/gl_rendering_context.cpp, line 156)

For example, here is a callstack that leads to an OpenGL with an error on SamplesRunner under windows:

`````
0x0000016c8c0ca000 "ERROR INVALID_ENUM(1280) in glPixelStorei\n"

>	SamplesRunner.exe!BABYLON::GL::glad_post_call_callback(const char * name, void * __formal, int __formal, ...) Line 156	C++
 	SamplesRunner.exe!glad_debug_impl_glPixelStorei(unsigned int arg0, int arg1) Line 4594	C
 	SamplesRunner.exe!BABYLON::GL::GLRenderingContext::pixelStorei(unsigned int pname, int param) Line 1025	C++
 	babyloncpp_d.dll!BABYLON::Engine::Engine(BABYLON::ICanvas * canvas, const BABYLON::EngineOptions & options) Line 200	C++
 	babyloncpp_d.dll!BABYLON::Engine::New<BABYLON::ICanvas * &>(BABYLON::ICanvas * & <args_0>) Line 153	C++
 	babyloncpp_d.dll!BABYLON::IRenderableScene::initialize(BABYLON::ICanvas * canvas) Line 34	C++
 	SamplesRunner.exe!BABYLON::ImGuiSceneWidget::setRenderableScene(std::shared_ptr<BABYLON::IRenderableScene> scene) Line 42	C++
 	SamplesRunner.exe!BABYLON::impl::BabylonInspectorApp::setRenderableScene(std::shared_ptr<BABYLON::IRenderableScene> scene) Line 167	C++
 	SamplesRunner.exe!BABYLON::impl::BabylonInspectorApp::RunApp::__l2::<lambda>() Line 68	C++
 	[External Code]	
 	SamplesRunner.exe!ImGuiUtils::ImGuiRunner::RunGui(std::function<bool __cdecl(void)> guiFunction, ImGuiUtils::ImGuiRunner::AppWindowParams appWindowParams, std::function<void __cdecl(void)> postInitFunction) Line 158	C++
 	SamplesRunner.exe!BABYLON::impl::BabylonInspectorApp::RunApp(std::shared_ptr<BABYLON::IRenderableScene> initialScene, const BABYLON::SceneWithInspectorOptions & options) Line 69	C++
 	SamplesRunner.exe!BABYLON::runSceneWithInspector(std::shared_ptr<BABYLON::IRenderableScene> scene, BABYLON::SceneWithInspectorOptions options) Line 253	C++
 	SamplesRunner.exe!main(int argc, char * * argv) Line 61	C++

````

Good luck

**Comment by samdauwe** [comment]
Hello Pascal,

Thanks for the advice! I tried enabled the debugging, and it gave a couple of OpenGL errors. Unfortunately, resolving those errors did not resolve the rendering problems.

Then I had a look in the commits to track down the last working version. The version of 20/08 still worked properly. After that date I mainly worked on porting 3 classes: Effect, Scene and Engine. Changing anything in those files trigger a long rebuild so after some trial-and-error I decided to restore those classes to their 20/08 versions and now I am getting your SampleRunner working on Linux (and mouse controls are also working again):

Screenshot_20190828_215912

I did not try yet on Windows, this will be for tomorrow.

For porting those 3 files, I will do smaller changes and test if these small changes break anything, but porting those files can wait. I am going to focus now on resolving the issues with the samples you reported.

Have a nice evening,
Sam

**Comment by pthom** [comment]
Hello Sam,

If the compilation is too long, you can try to install « ccache » on Linux.
It caches all the compilation you do, so that if you recompile exactly the same
File with the same includes and compile options it is done instantly. Don’t worry
It is very reliable.

See here for an example that shows how to enable it

1110027fe3db34683dce41aaeb6a4152c5ee5626

Cheers

**Comment by samdauwe** [comment]
Hello Pascal,

Thanks for this information! I never tried it before but it seems really easy to enable it. I will try it out.

I tried the SampleRunner on Windows and it works very good, nice work!

Best regards,
Sam

**Pull request merged**
