### PR TITLE
Samples info

### PR DESCRIPTION
**Pull request by pthom**
Hello Sam,

Here is another PR that makes it even easier to handle the samples status and screenshots.

Status after this PR:

````
    stats {"empty3d":6,"success":253,"tooSlowOrHung":4,"unhandledException":7,"unknown":0} / Nb Manual Failure:14
````

### Features

The "experimental" checkbox enables to precisely select the failing examples by failure type:

- the types "success", "unhandledException", "tooSlowOrHung", "empty3d", "unknown" are discovered automatically when running `BabylonStudio -a`  
- The checkbox "With manual run failures" enables to filter the example where a failure was detected by manual inspection (i.e incorrect rendering that you detect yourself)

image

You can set the "manual failure" flag when running the samples like this:

image

### Where is the samples status  this info located?

* `assets/screenshots/ScreenshotsData/*.jpg` contains all the screenshots
* `assets/screenshots/ScreenshotsData/aa_runStatus.json` contains all the statuses.
* `assets/screenshots/ScreenshotsData/aa_sampleRunManualInfo.json` contains all the manual run infos
* `assets/samples_info.json` contains the samples descriptions and hyperlinks

(the 'aa' prefix is there so that these files appear first by alphabetical order...) 

### Manual failures status:

Please look at the scenes which I annotated as "manual failures". There is perhaps an easy fix for some of them.
If you look for "manual failures" matching "inverted", you will see 6 samples for which I suspect that the texture normals are inverted.

image

For example, in the fire Material Scene, the table texture is located on the lower side of the table
image

### How to update / commit new screenshots:

* Run `BabylonStudio -a`, it will generate new screenshots and update `aa_runStatus.json`
* The new script `codegeneration/compare_screenshots_git.py` is launched automatically after this, and it will remove all the screenshots that do not differ much (so that we can commit only the really updated screenshots) 

_Important Note_ : this script requires python3 and some additional modules, please read the documentation inside it. You can install its required modules with
````
pip3 install opencv-python scikit-image imutils
````

### Answers to your week-end debugging session message

> here are the updated numbers after a weekend of debugging:
> {"nbEmptyRendering":5,"nbProcessFailures":16,"nbProcessHung":11,"nbSuccess":249}

This is an awesome job! Great!

> Restoring the sync file loading functions have a side effect in the BabylonStudio, all thumbnails are inverted in the Y-axis.

I did not see that, could you post a screenshot?

>     I temporarily disabled all aync io function calls (with this commit) and the master branch is now using the file loading functions from the more stable version of Nov 22nd. 

I think this commit might be unnecessary. 
Here are my result before and after reverting it: they are identical

````
Before revert:
    stats {"empty3d":6,"success":252,"tooSlowOrHung":4,"unhandledException":7,"unknown":0} / Nb Manual Failure:14

After revert:
        {"empty3d":6,"success":252,"tooSlowOrHung":4,"unhandledException":7,"unknown":0} / Nb Manual Failure:14
````

Could you confirm this on your side?

### Status of the async mode

If I revert your commit, and then run `BabylonStudio -a -A` (i.e take screenshots in async mode), we get the following results:

````
stats {"empty3d":2,"success":136,"tooSlowOrHung":5,"unhandledException":127,"unknown":0} / Nb Manual Failure:14
````

I think that once this debugging session is ended in  the master branch in sync mode, we can open a new 'develop' branch where we can concentrate on fixing the async mode.

Cheers,
Pascal

### CODE REVIEW

**Comment by pthom** [comment]
PS: Some examples run at 1000+ fps, which make it difficult to use them. Do you remember what can be done in order to restore a sane FPS (maybe something inside runner_sdl.cpp)?

image

**Comment by samdauwe** [comment]
Hello Pascal,

> 
> Here is another PR that makes it even easier to handle the samples status and screenshots.
> 
> Status after this PR:
> 
> ```
>     stats {"empty3d":6,"success":253,"tooSlowOrHung":4,"unhandledException":7,"unknown":0} / Nb Manual Failure:14
> ```
> 
> ### Features
> 
> The "experimental" checkbox enables to precisely select the failing examples by failure type:
> 
>     * the types "success", "unhandledException", "tooSlowOrHung", "empty3d", "unknown" are discovered automatically when running `BabylonStudio -a`
> 
>     * The checkbox "With manual run failures" enables to filter the example where a failure was detected by manual inspection (i.e incorrect rendering that you detect yourself)
> 
> 
> image
> 
> You can set the "manual failure" flag when running the samples like this:
> 
> image
> ### Where is the samples status this info located?
> 
>     * `assets/screenshots/ScreenshotsData/*.jpg` contains all the screenshots
> 
>     * `assets/screenshots/ScreenshotsData/aa_runStatus.json` contains all the statuses.
> 
>     * `assets/screenshots/ScreenshotsData/aa_sampleRunManualInfo.json` contains all the manual run infos
> 
>     * `assets/samples_info.json` contains the samples descriptions and hyperlinks
> 
> 
> (the 'aa' prefix is there so that these files appear first by alphabetical order...)
> ### Manual failures status:
> 
> Please look at the scenes which I annotated as "manual failures". There is perhaps an easy fix for some of them.
> If you look for "manual failures" matching "inverted", you will see 6 samples for which I suspect that the texture normals are inverted.
> 
> image
> 
> For example, in the fire Material Scene, the table texture is located on the lower side of the table
> image
> ### How to update / commit new screenshots:
> 
>     * Run `BabylonStudio -a`, it will generate new screenshots and update `aa_runStatus.json`
> 
>     * The new script `codegeneration/compare_screenshots_git.py` is launched automatically after this, and it will remove all the screenshots that do not differ much (so that we can commit only the really updated screenshots)
> 
> 
> _Important Note_ : this script requires python3 and some additional modules, please read the documentation inside it. You can install its required modules with
> 
> ```
> pip3 install opencv-python scikit-image imutils
> ```
> 


This PR adds a lot of good features to the samples browser. It hides the examples that are not properly rendered and you can see what is wrong with them, using the right filters! Thanks! I am going to further test this on my side.


> ### Answers to your week-end debugging session message
> 
> > here are the updated numbers after a weekend of debugging:
> > {"nbEmptyRendering":5,"nbProcessFailures":16,"nbProcessHung":11,"nbSuccess":249}
> 
> This is an awesome job! Great!
> 
> > Restoring the sync file loading functions have a side effect in the BabylonStudio, all thumbnails are inverted in the Y-axis.
> 
> I did not see that, could you post a screenshot?
> 
> > ```
> > I temporarily disabled all aync io function calls (with this commit) and the master branch is now using the file loading functions from the more stable version of Nov 22nd. 
> > ```
> 
> I think this commit might be unnecessary.
> Here are my result before and after reverting it: they are identical
> 
> ```
> Before revert:
>     stats {"empty3d":6,"success":252,"tooSlowOrHung":4,"unhandledException":7,"unknown":0} / Nb Manual Failure:14
> 
> After revert:
>         {"empty3d":6,"success":252,"tooSlowOrHung":4,"unhandledException":7,"unknown":0} / Nb Manual Failure:14
> ```
> 
> Could you confirm this on your side?
> ### Status of the async mode
> 
> If I revert your commit, and then run `BabylonStudio -a -A` (i.e take screenshots in async mode), we get the following results:
> 
> ```
> stats {"empty3d":2,"success":136,"tooSlowOrHung":5,"unhandledException":127,"unknown":0} / Nb Manual Failure:14
> ```


Hmmm, the flipped screenshots in the sample browser were related to the sync file loading methods I added. I removed those functions and restored the async io calls with [this commit](https://github.com/samdauwe/BabylonCpp/commit/84c97d2d3a3a7d1cca47748efc67b610dde13c98) and now the screenshots seem to be rendering fine again. The examples are also rendering fine, the issues I had this weekend were probably related to other changes.

> I think that once this debugging session is ended in the master branch in sync mode, we can open a new 'develop' branch where we can concentrate on fixing the async mode.

Good plan! I will concentrate on the "empty3d":6 and "unhandledException":7 first, should hopefully now take that long to fix those (1-2 weeks).

> Cheers,
> Pascal

Cheers,
Sam

**Comment by samdauwe** [comment]
> PS: Some examples run at 1000+ fps, which make it difficult to use them. Do you remember what can be done in order to restore a sane FPS (maybe something inside runner_sdl.cpp)?
> 
> image

I tried running the _RollercoasterScene_ example, but on my side it is running on 60 fps.

Could it be that you are using the software renderer on your side?

I saw some forums posts about people mentioning that the VSync setting is ignored when using the software renderer. There are some suggestions to resolved this issue like on [this page](https://www.reddit.com/r/sdl/comments/du2jva/how_to_enable_vsync_with_software_rendering_in/) but I cannot verify it on my side because I cannot reproduce the 1000+ fps issue.

Another approach is to add a timeout/sleep in your code, like for instance illustrated on [this page](https://stackoverflow.com/questions/30953858/sdl2-vsync-not-working).

Hope it helps!

Cheers
Sam

**Comment by samdauwe** [comment]
Hello Pascal,

I already got the request last year to add the BabylonCpp project to the official BabylonJS documentation. Last week, related to [this forum topic](https://forum.babylonjs.com/t/about-babylonnative-and-babyloncpp/8209), I was asked again by the lead developer of BabylonJS.

Now that we are approaching a stable version and we have a lot of functionality that can be shown, I think it is time to give some more visibility to the project. Therefore, I was planning to create a couple of documentation pages in the official BabylonJS doc covering the following topics:
- Introduction to BabylonCpp
  * Context, comparison with BabylonNative
- Getting started
  * Git repo layout desciption
  * Building the project
  * BabylonStudio
    * Configuring visual studio
    * Explanation of the GUI (panels, menu options)
    * Command-line arguments
- Adding an example
  * Steps needed to add an example
  * Changing example code at runtime from within BabylonStudio

What do you think about the topics, is there anything I am forgetting? If you like contributing to some of the documentation topics let me know, then we can divide the work. I am planning to start working on this tomorrow.

Thanks,
Sam

**Comment by pthom** [comment]
Hi Sam,

The forum thread is actually quite interesting! Your answer was detailed and honest about the status of the project.

It is a good idea to add some documentation. Keep me posted when you start pushing on your documentation fork, I will try to help. I might be a little busy these next days and this week-end however. 

Do you plan to make another post on the forum that would introduce BablyonCpp together with its  documentation? If so, I would be happy to participate to it.
Also, such a post may be a good time to mention that contributors are welcome, because I think the help of some people with a good experience in BabylonJs & C++ might be useful. What do you think?  

I spent a few hours today trying to restore the emscripten build, and then exploring the [promise-cpp](https://github.com/xhawk18/promise-cpp) library, which is powerful but complex: still a lot to explore though. It is not an easy journey :-)

**Comment by samdauwe** [comment]
Hello Pascal,

Yeah, and there is also nice positive comments on te project 😁

I have a first section ready for the doc, but I will have most time available in the weekend. So it will be probably Sunday evening that I send you an update what I have so far.

Yes, I am planning to do an update on the project and give more details about the changes since my previous forum post in 2018. Having extra contributors would really help a lot. Maybe we can convince people with the demo video. I Will let you Knox when I Will creatie the post.

The promise-cpp looks indeed complex, Getting the asynchronous Asset loading with all the callbacks is not an easy task. It is a real challenge!

Today I fixed the issue of missing nodes in the Inspector scene graph panel.

Cheers,
Sam

**Comment by samdauwe** [comment]
Hello Pascal,

this week I looked further into the samples that were failing with an unhandled Exception.

The following six examples were fixed: ExtrudePolygonScene, PolyhedronScene, BuildingsSpsScene, LightedSpsScene, TrianglesSpsScene and ShaderMaterialScene.

Only 1 unhandledException type sample is left named "VolumetricLightScatteringScene". Fixing the 3 sprite examples that are not rendering is next on my list.

Cheers,
Sam

**Pull request merged**
