### PR TITLE
Fix engine

### PR DESCRIPTION
**Pull request by pthom**
Hello again

Here are some more simple bug fixes:

- texImage2D should be able to accept nullptr (this solves many issues in the samples "LoadXXX")
- Fix two bug in the animation:
  - Set _animationTime to 0 a construction
  - Copy __activeAnimatables (vector<AnimatablePtr>) before looping inside _animate()
 because activeAnimatable->_animate can remove items from _scene->_activeAnimatables
- material_helper: BonesPerMesh is an intDef (not a boolDef)

### CODE REVIEW

**Comment by pthom** [comment]
PS: I am now studying the possibility to render in a texture.

**Comment by samdauwe** [comment]
Thanks for the fixes! I merged them into the master branch.

**Comment by samdauwe** [comment]
Hello again,

What approach do you use to render a scene into a texture?

Today I had some time to look into how to render to a texture using Framebuffers (as explained [on this page](https://learnopengl.com/#!Advanced-OpenGL/Framebuffers)).

I am able to render to a texture and show the image in an ImGUI window as illustrated in the screenshot below:

materials_scene

At this moment it is still in experimenting phase and a lot of functionality needs to be implemented:
- Handle window resizing 
- Couple the keyboard / mouse input
- Test with ImGui docking branch
- Integrate inspector widgets

I can share the code if you are interested, otherwise I will commit a more functional and cleaned up version by the end of this week.

Best regards,
Sam

**Comment by pthom** [comment]
Oups, really sorry. I just stumbled upon your message after I posted my last PR, where it seems I worked on exactly the same subject. I hope there will not be too many conflicts.

**Pull request merged**
